#Single file to run compose up

version: "3"
services:
  unicorn-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #     -PORT=3000
    env_file:
      - ./.env
